/* ============================================================
   MURAD LEARNING PLANNER - English Translations
   ============================================================ */

const LANG_EN = {
  // ── Navigation ─────────────────────────────────────────────
  'nav.main': 'Main',
  'nav.dashboard': 'Dashboard',
  'nav.weekly': 'Weekly Schedule',
  'nav.patterns': 'Patterns',
  'nav.patternA': 'Pattern A - New Learning',
  'nav.patternB': 'Pattern B - Reinforcement',
  'nav.patternC': 'Pattern C - Integration',
  'nav.patternD': 'Pattern D - Closure',
  'nav.tools': 'Tools',
  'nav.settings': 'Settings',
  'nav.ai': 'AI System',
  'nav.ai.workspace': 'AI Workspace',
  'nav.ai.analytics': 'AI Analytics',
  'nav.ai.automations': 'AI Automations',
  'nav.ai.personality': 'AI Personality',
  'nav.ai.settings': 'AI Settings',

  // ── User ────────────────────────────────────────────────────
  'user.role': 'Learning Planner',

  // ── Dashboard ───────────────────────────────────────────────
  'dashboard.title': 'Dashboard',
  'dashboard.subtitle': 'Advanced Daily Learning System',
  'dashboard.weekOverview': 'Week Overview',
  'dashboard.todayProgress': "Today's Progress",
  'dashboard.weekStats': 'Week Statistics',

  // ── Status Cards ────────────────────────────────────────────
  'status.week': 'Current Week',
  'status.pattern': 'Current Pattern',
  'status.day': 'Current Day',
  'status.session': 'Session',
  'status.block': 'Current Block',
  'status.timer': 'Timer',
  'status.next': 'Next Block',
  'status.status': 'Status',
  'status.active': 'Active',
  'status.idle': 'Idle',

  // ── Weekly ──────────────────────────────────────────────────
  'weekly.title': 'Weekly Pattern Board',
  'weekly.subtitle': 'Editable Weekly Schedule',
  'weekly.week': 'Week',
  'weekly.saved': 'Auto-saved',

  // ── Table headers ───────────────────────────────────────────
  'table.day': 'Day',
  'table.pattern': 'Pattern',
  'table.actions': 'Actions',

  // ── Buttons ─────────────────────────────────────────────────
  'btn.exportWeekly': 'Export Weekly PDF',
  'btn.exportDaily': 'Export Daily PDF',
  'btn.exportMonthly': 'Export Monthly PDF',
  'btn.newWeek': 'New Week',
  'btn.save': 'Save',
  'btn.back': 'Back',
  'btn.open': 'Open',
  'btn.cancel': 'Cancel',
  'btn.delete': 'Delete',
  'btn.edit': 'Edit',
  'btn.add': 'Add',
  'btn.test': 'Test',
  'btn.confirm': 'Confirm',
  'btn.close': 'Close',
  'btn.send': 'Send',
  'btn.generate': 'Generate',
  'btn.apply': 'Apply',
  'btn.reset': 'Reset',
  'btn.export': 'Export',
  'btn.import': 'Import',
  'btn.copy': 'Copy',
  'btn.run': 'Run',
  'btn.stop': 'Stop',
  'btn.enable': 'Enable',
  'btn.disable': 'Disable',

  // ── Days ────────────────────────────────────────────────────
  'day.sat': 'Saturday',
  'day.sun': 'Sunday',
  'day.mon': 'Monday',
  'day.tue': 'Tuesday',
  'day.wed': 'Wednesday',
  'day.thu': 'Thursday',
  'day.fri': 'Friday',

  // ── Patterns ────────────────────────────────────────────────
  'pattern.a.name': 'Pattern A',
  'pattern.a.title': 'Learning New Concepts',
  'pattern.a.tag': 'New Learning Day',
  'pattern.a.goal': "Today's Goal",
  'pattern.a.goalText': 'This day is dedicated to acquiring new knowledge for the first time. Focus is on understanding, not mastery.',
  'pattern.a.example': 'Practical Example',
  'pattern.a.exampleText': 'Learn Functions for the first time • Write your first simple Function',
  'pattern.a.focus': 'What to Focus On',
  'pattern.a.focusText': 'Initial understanding • First exposure • First implementation',
  'pattern.a.avoid': 'What to Avoid',
  'pattern.a.avoidText': 'Over-diving • Memorizing details • Worrying about mastery',
  'pattern.b.name': 'Pattern B',
  'pattern.b.title': 'Reinforcement Day',
  'pattern.b.tag': 'Reinforcement Day',
  'pattern.b.goal': "Today's Goal",
  'pattern.b.goalText': 'This day is for reinforcing previous knowledge. No big new concepts.',
  'pattern.b.example': 'Practical Example',
  'pattern.b.exampleText': 'Solve 20 problems on Functions • Improve code',
  'pattern.b.focus': 'What to Focus On',
  'pattern.b.focusText': 'Solving problems • Improving code • Deliberate practice',
  'pattern.b.avoid': 'What to Avoid',
  'pattern.b.avoidText': 'Learning big new concepts',
  'pattern.c.name': 'Pattern C',
  'pattern.c.title': 'Integration Day',
  'pattern.c.tag': 'Most Important Day',
  'pattern.c.goal': "Today's Goal",
  'pattern.c.goalText': 'This is the most important day. Connect all the concepts you learned.',
  'pattern.c.example': 'Practical Example',
  'pattern.c.exampleText': 'Functions + Variables + Algorithms → An integrated program',
  'pattern.c.focus': 'What to Focus On',
  'pattern.c.focusText': 'Connecting concepts • Building something complete • Finding relationships',
  'pattern.c.avoid': 'What to Avoid',
  'pattern.c.avoidText': 'Learning new concepts • Working on each topic in isolation',
  'pattern.d.name': 'Pattern D',
  'pattern.d.title': 'Weekly Closure',
  'pattern.d.tag': 'Test & Evaluation',
  'pattern.d.goal': "Today's Goal",
  'pattern.d.goalText': "This day is for measuring your true understanding. Test yourself without references.",
  'pattern.d.example': 'Practical Example',
  'pattern.d.exampleText': 'Solve a math test from memory • Write a program without references',
  'pattern.d.focus': 'What to Focus On',
  'pattern.d.focusText': 'Honest self-testing • Identifying gaps • Clear closure',
  'pattern.d.avoid': 'What to Avoid',
  'pattern.d.avoidText': 'Looking at references during tests • Being lenient in self-evaluation',

  // ── Block names ─────────────────────────────────────────────
  'block.review': 'Review',
  'block.math': 'Mathematics',
  'block.break': 'Break',
  'block.programming': 'Programming',
  'block.cs': 'Computer Science',
  'block.lunch': 'Lunch',
  'block.integration': 'Integration',
  'block.project': 'Project',
  'block.closing': 'Closing',

  // ── Panel ───────────────────────────────────────────────────
  'panel.title': 'Block Details',
  'panel.name': 'Block Name',
  'panel.time': 'Time',
  'panel.activity': 'Activity',
  'panel.goal': 'Goal',
  'panel.learn': 'What will I learn?',
  'panel.apply': 'What will I apply?',
  'panel.notes': 'Notes',
  'panel.outputs': 'Expected Outputs',
  'panel.sound': 'Alarm Sound',

  // ── Integration ─────────────────────────────────────────────
  'integration.title': 'Integration Builder',
  'integration.subtitle': 'Visually connect concepts',
  'integration.math': 'Math Concept',
  'integration.prog': 'Programming Concept',
  'integration.cs': 'CS Concept',
  'integration.result': 'Integrated Output',
  'integration.relation': 'How do they connect?',
  'integration.build': 'Build Diagram',

  // ── Modal ───────────────────────────────────────────────────
  'modal.blockFinished': 'Block Finished!',
  'modal.nextBlock': 'Next Block:',
  'modal.startNext': 'Start Next Block',
  'modal.close': 'Close',

  // ── Settings ────────────────────────────────────────────────
  'settings.title': 'Settings',
  'settings.subtitle': 'Customize your learning experience',
  'settings.sound': 'Sound Settings',
  'settings.defaultSound': 'Default Alarm Sound',
  'settings.volume': 'Volume',
  'settings.repeat': 'Repeat Alarm',
  'settings.repeatCount': 'Repeat Count',
  'settings.duration': 'Alarm Duration',
  'settings.uploadSound': 'Upload Custom Sound',
  'settings.upload': 'Upload Sound File',
  'settings.uploadHint': 'MP3, WAV, OGG, M4A',
  'settings.customSounds': 'My Custom Sounds',
  'settings.general': 'General Settings',
  'settings.language': 'Language',
  'settings.theme': 'Theme',
  'settings.dark': 'Dark',
  'settings.light': 'Light',
  'settings.userName': 'Username',
  'settings.weekStart': 'Week Start Date',
  'settings.notifications': 'Notifications',
  'settings.perBlockSound': 'Custom Sound Per Block',

  // ── Timer ───────────────────────────────────────────────────
  'timer.start': 'Start',
  'timer.pause': 'Pause',
  'timer.resume': 'Resume',
  'timer.reset': 'Reset',
  'timer.skip': 'Skip',
  'timer.details': 'Details',

  // ── Toast ───────────────────────────────────────────────────
  'toast.saved': 'Saved successfully',
  'toast.error': 'An error occurred',
  'toast.pdfExport': 'Exporting PDF...',
  'toast.pdfDone': 'PDF exported successfully',
  'toast.copied': 'Copied to clipboard',
  'toast.deleted': 'Deleted successfully',
  'toast.added': 'Added successfully',
  'toast.langChanged': 'Language changed to English',
  'toast.providerSaved': 'Provider saved successfully',
  'toast.providerDeleted': 'Provider deleted',
  'toast.testSuccess': 'Connection successful',
  'toast.testFailed': 'Connection failed',

  // ── Sessions ────────────────────────────────────────────────
  'session.morning': 'Morning Session',
  'session.afternoon': 'Afternoon Session',

  // ── Floating Dock ───────────────────────────────────────────
  'dock.aiAssistant': 'AI Assistant',
  'dock.userGuide': 'User Guide',
  'dock.notifications': 'Notifications',
  'dock.quickActions': 'Quick Actions',
  'dock.openFull': 'Open Full',
  'dock.close': 'Close',

  // ── AI Workspace ────────────────────────────────────────────
  'ai.workspace.title': 'AI Workspace',
  'ai.workspace.newChat': 'New Chat',
  'ai.workspace.search': 'Search conversations...',
  'ai.workspace.conversations': 'Conversations',
  'ai.workspace.pinned': 'Pinned',
  'ai.workspace.noConversations': 'No conversations yet',
  'ai.workspace.startNew': 'Start a new conversation',
  'ai.workspace.welcome': 'How can I help you today?',
  'ai.workspace.welcomeSub': "I'm your personal AI assistant. I can help you plan, learn, and analyze.",
  'ai.workspace.inputPlaceholder': 'Type your message here...',
  'ai.workspace.send': 'Send',
  'ai.workspace.stop': 'Stop',
  'ai.workspace.voice': 'Voice input',
  'ai.workspace.attach': 'Attach file',
  'ai.workspace.image': 'Attach image',
  'ai.workspace.tts': 'Text to speech',
  'ai.workspace.copy': 'Copy',
  'ai.workspace.regenerate': 'Regenerate',
  'ai.workspace.speak': 'Speak',
  'ai.workspace.mode.chat': 'Chat',
  'ai.workspace.mode.analyze': 'Analyze',
  'ai.workspace.mode.plan': 'Plan',
  'ai.workspace.mode.teach': 'Teach',
  'ai.workspace.typing': 'Typing...',
  'ai.workspace.loadMore': 'Load more',
  'ai.workspace.clearAll': 'Clear all',
  'ai.workspace.exportChat': 'Export chat',
  'ai.workspace.deleteChat': 'Delete chat',
  'ai.workspace.pinChat': 'Pin chat',
  'ai.workspace.unpinChat': 'Unpin chat',
  'ai.workspace.renameChat': 'Rename',
  'ai.workspace.noProvider': 'No provider configured',
  'ai.error.emptyResponse': 'No response received. Please check your provider settings.',
  'ai.workspace.configureFirst': 'Please set up an AI provider first in AI Settings',
  'ai.workspace.multiProvider': 'Switch provider',
  'ai.workspace.fileAttached': 'File attached',
  'ai.workspace.imageAttached': 'Image attached',
  'ai.workspace.dragDrop': 'Drag & drop files here',
  'ai.workspace.suggestions': 'Suggestions',
  'ai.workspace.sugg1': 'Analyze my progress this week',
  'ai.workspace.sugg2': "Suggest tomorrow's study plan",
  'ai.workspace.sugg3': 'Create a quick review',
  'ai.workspace.sugg4': 'Talk to me about my goals',

  // ── AI Settings ─────────────────────────────────────────────
  'ai.settings.title': 'AI Settings',
  'ai.settings.providers': 'AI Providers',
  'ai.settings.addProvider': 'Add Provider',
  'ai.settings.editProvider': 'Edit Provider',
  'ai.settings.deleteProvider': 'Delete Provider',
  'ai.settings.testConnection': 'Test Connection',
  'ai.settings.providerName': 'Provider Name',
  'ai.settings.apiKey': 'API Key',
  'ai.settings.baseUrl': 'Base URL',
  'ai.settings.models': 'Models',
  'ai.settings.addModel': 'Add Model',
  'ai.settings.modelName': 'Model Name',
  'ai.settings.modelId': 'Model ID',
  'ai.settings.contextWindow': 'Context Window',
  'ai.settings.maxTokens': 'Max Tokens',
  'ai.settings.temperature': 'Temperature',
  'ai.settings.inputCost': 'Input Cost',
  'ai.settings.outputCost': 'Output Cost',
  'ai.settings.status.connected': 'Connected',
  'ai.settings.status.failed': 'Failed',
  'ai.settings.status.invalid_key': 'Invalid API Key',
  'ai.settings.status.invalid_model': 'Invalid Model',
  'ai.settings.status.rate_limited': 'Rate Limited',
  'ai.settings.status.quota_exceeded': 'Quota Exceeded',
  'ai.settings.status.offline': 'Provider Offline',
  'ai.settings.status.unknown': 'Unknown',
  'ai.settings.status.untested': 'Not Tested',
  'ai.settings.diagnostics': 'Diagnostics Center',
  'ai.settings.debugger': 'AI Request Debugger',
  'ai.settings.latency': 'Latency',
  'ai.settings.tokensUsed': 'Tokens Used',
  'ai.settings.requestCount': 'Request Count',
  'ai.settings.errorCount': 'Error Count',
  'ai.settings.lastResponse': 'Last Response',
  'ai.settings.lastError': 'Last Error',
  'ai.settings.clearLogs': 'Clear Logs',
  'ai.settings.noLogs': 'No logs yet',
  'ai.settings.activeProvider': 'Active Provider',
  'ai.settings.activeModel': 'Active Model',

  // ── AI Analytics ────────────────────────────────────────────
  'ai.analytics.title': 'AI Analytics',
  'ai.analytics.performance': 'Performance',
  'ai.analytics.productivity': 'Productivity',
  'ai.analytics.focus': 'Focus',
  'ai.analytics.bestSubject': 'Best Subject',
  'ai.analytics.weakSubject': 'Weakest Subject',
  'ai.analytics.missedSessions': 'Missed Sessions',
  'ai.analytics.completionRate': 'Completion Rate',
  'ai.analytics.burnout': 'Burnout Risk',
  'ai.analytics.recommendations': 'Recommendations',
  'ai.analytics.trend': 'Trend',
  'ai.analytics.daily': 'Daily',
  'ai.analytics.weekly': 'Weekly',
  'ai.analytics.monthly': 'Monthly',
  'ai.analytics.insights': 'Insights',
  'ai.analytics.noData': 'Not enough data for analysis',
  'ai.analytics.memory': 'Memory',
  'ai.analytics.memoryItems': 'Memory Items',
  'ai.analytics.addMemory': 'Add Memory',
  'ai.analytics.clearMemory': 'Clear Memory',
  'ai.analytics.generateReport': 'Generate Report',
  'ai.analytics.score': 'Score',
  'ai.analytics.low': 'Low',
  'ai.analytics.medium': 'Medium',
  'ai.analytics.high': 'High',
  'ai.analytics.excellent': 'Excellent',

  // ── AI Automations ──────────────────────────────────────────
  'ai.auto.title': 'AI Automations',
  'ai.auto.new': 'New Automation',
  'ai.auto.templates': 'Templates',
  'ai.auto.noAutomations': 'No automations yet',
  'ai.auto.trigger': 'Trigger',
  'ai.auto.action': 'Action',
  'ai.auto.condition': 'Condition',
  'ai.auto.name': 'Automation Name',
  'ai.auto.enabled': 'Enabled',
  'ai.auto.disabled': 'Disabled',
  'ai.auto.run': 'Run',
  'ai.auto.delete': 'Delete',
  'ai.auto.lastRun': 'Last Run',
  'ai.auto.never': 'Never run',
  'ai.auto.trigger.session_complete': 'When session completed',
  'ai.auto.trigger.streak_milestone': 'When streak milestone reached',
  'ai.auto.trigger.inactivity': 'When inactive for N days',
  'ai.auto.trigger.score_drop': 'When score drops',
  'ai.auto.trigger.weekly_start': 'On week start',
  'ai.auto.trigger.daily_start': 'On day start',
  'ai.auto.trigger.manual': 'Manual',
  'ai.auto.action.send_reminder': 'Send reminder',
  'ai.auto.action.create_schedule': 'Create schedule',
  'ai.auto.action.generate_report': 'Generate report',
  'ai.auto.action.increase_streak': 'Increase streak',
  'ai.auto.action.suggest_review': 'Suggest review session',
  'ai.auto.action.send_notification': 'Send notification',
  'ai.auto.if': 'IF',
  'ai.auto.then': 'THEN',
  'ai.auto.addCondition': 'Add Condition',
  'ai.auto.addAction': 'Add Action',

  // ── AI Personality ──────────────────────────────────────────
  'ai.personality.title': 'AI Personality',
  'ai.personality.profiles': 'Profiles',
  'ai.personality.addProfile': 'Add Profile',
  'ai.personality.name': 'Profile Name',
  'ai.personality.assistantName': 'Assistant Name',
  'ai.personality.tone': 'Tone',
  'ai.personality.tone.friendly': 'Friendly',
  'ai.personality.tone.professional': 'Professional',
  'ai.personality.tone.motivational': 'Motivational',
  'ai.personality.tone.strict': 'Strict',
  'ai.personality.tone.casual': 'Casual',
  'ai.personality.language': 'Assistant Language',
  'ai.personality.teachingStyle': 'Teaching Style',
  'ai.personality.style.socratic': 'Socratic',
  'ai.personality.style.direct': 'Direct',
  'ai.personality.style.storytelling': 'Storytelling',
  'ai.personality.style.examples': 'By Examples',
  'ai.personality.responseLength': 'Response Length',
  'ai.personality.length.short': 'Short',
  'ai.personality.length.medium': 'Medium',
  'ai.personality.length.long': 'Long',
  'ai.personality.systemPrompt': 'System Prompt',
  'ai.personality.behaviourRules': 'Behaviour Rules',
  'ai.personality.addRule': 'Add Rule',
  'ai.personality.save': 'Save Personality',
  'ai.personality.reset': 'Reset to Default',
  'ai.personality.active': 'Active Profile',
  'ai.personality.setActive': 'Set as Active',

  // ── AI Dashboard Widget ──────────────────────────────────────
  'ai.widget.title': 'AI Daily Intelligence Report',
  'ai.widget.generating': 'Generating report...',
  'ai.widget.todayAnalysis': "Today's Analysis",
  'ai.widget.risks': 'Risks',
  'ai.widget.opportunities': 'Opportunities',
  'ai.widget.suggestedActions': 'Suggested Actions',
  'ai.widget.motivation': 'Motivation Insights',
  'ai.widget.refresh': 'Refresh Report',
  'ai.widget.autoGenerated': 'Auto-generated daily',

  // ── Notifications ────────────────────────────────────────────
  'notif.title': 'Notifications',
  'notif.noNotifications': 'No notifications',
  'notif.clearAll': 'Clear All',
  'notif.markRead': 'Mark as read',
  'notif.ago': 'ago',
  'notif.just': 'just now',
  'notif.min': 'min',
  'notif.hour': 'hour',
  'notif.day': 'day',

  // ── Quick Actions ────────────────────────────────────────────
  'quick.title': 'Quick Actions',
  'quick.newSession': 'New Session',
  'quick.askAI': 'Ask AI',
  'quick.viewSchedule': 'View Schedule',
  'quick.addGoal': 'Add Goal',

  // ── Provider Validation ──────────────────────────────────────
  'validation.testing': 'Testing...',
  'validation.connected': 'Connected successfully',
  'validation.failed': 'Connection failed',
  'validation.invalid_key': 'Invalid API key',
  'validation.invalid_model': 'Invalid model ID',
  'validation.rate_limited': 'Rate limit exceeded',
  'validation.quota_exceeded': 'Quota exceeded',
  'validation.offline': 'Provider offline',
  'validation.saved': 'Saved - connection successful',
  'validation.saveBlocked': 'Cannot save - test failed',
  'validation.noApiKey': 'Please enter an API key',
  'validation.noModel': 'Please add at least one model',
  'validation.fillRequired': 'Please fill all required fields',

  // ── AI Actions ───────────────────────────────────────────────
  'action.creating': 'Creating...',
  'action.updating': 'Updating...',
  'action.success': 'Done successfully',
  'action.failed': 'Operation failed',
  'action.scheduleCreated': 'Schedule created',
  'action.goalCreated': 'Goal created',
  'action.noteCreated': 'Note created',
  'action.navigated': 'Navigated',
  'action.planOptimized': 'Plan optimized',

  // ── Diagnostics (P8) ────────────────────────────────────────
  'diag.title': 'Diagnostics Center',
  'diag.empty': 'No diagnostic data yet',
  'diag.emptyHint': 'Test a provider connection or send an AI message first',
  'diag.clearAll': 'Clear All',
  'diag.clear': 'Clear',
  'diag.model': 'Model',
  'diag.latency': 'Latency',
  'diag.tokens': 'Tokens Used',
  'diag.requests': 'Requests',
  'diag.errors': 'Errors',
  'diag.successRate': 'Success Rate',
  'diag.lastError': 'Last Error',
  'diag.lastSuccess': 'Last Success',

  // ── Stabilization / Provider Form ───────────────────────────
  'ai.settings.providerType': 'Provider Type',
  'ai.settings.icon': 'Icon',
  'ai.settings.color': 'Color',
  'ai.settings.customHeaders': 'Custom Headers',
  'ai.settings.description': 'Description',
  'ai.settings.active': 'Active',
  'ai.settings.setActive': 'Set Active',
  'ai.settings.enable': 'Enable / Disable',
  'ai.settings.noModels': 'No models',
  'ai.settings.addFirst': 'Add first model',
  'ai.settings.validateModel': 'Validate Model',
  'ai.settings.editModel': 'Edit Model',
  'ai.settings.capabilities': 'Capabilities',
  'ai.settings.confirmDelete': 'Are you sure you want to delete this provider?',
  'ai.settings.confirmDeleteModel': 'Delete this model?',
  'ai.settings.activeProvider': 'Active Provider',
  'ai.settings.activeModel': 'Active Model',
  'toast.deleted': 'Deleted',

  // ── Misc ─────────────────────────────────────────────────────
  'hello.name': 'Hello {name}',
};

